### PR TITLE
Docker tempate

### PR DESCRIPTION
**Pull request by ruffsl**
Adding support for Dockerfile generation using yaml setting files using new ros_buildfarm functions.

### CODE REVIEW

**Comment by ruffsl** [comment]
@tfoote , care to check this PR?

This should just contain the empy templates and entrypoint script OSRF docker images. It does contain some gazebo templates thus far though. Should be break those out somewhere else?

**Comment by scpeters** [comment]
I just wrote a template for drcsim. Should it go here?

**Comment by ruffsl** [comment]
@scpeters yes, this is the PR with the working ROS and Gazebo templates. In time we may want to separate the gazebo specific files.

**Comment by tfoote** [comment]
It sounds like we should merge this for better visibility. I guess you've been running things out of your fork @ruffsl in the mean time?

**Comment by ruffsl** [comment]
Yep, I think this is ripe for a merge.

**Pull request merged**
